import clients from "./data/clients.json";
import type { ProtocolType, StackLang, Threat } from "./threat-models";

export type LocBucket = "<1k" | "1-5k" | "5-15k" | ">15k";
export type Urgency = "Standard" | "Expedited";

export type ScopingInputs = {
  type: ProtocolType;
  stack: StackLang;
  loc: LocBucket;
  integrations: string[];
  upgradeable: boolean;
  urgency: Urgency;
};

export type Proposal = {
  weeksLow: number;
  weeksHigh: number;
  team: string[];
  deliverables: string[];
  comparable: { client: string; note: string } | null;
  caveats: string[];
};

const WEEKS: Record<LocBucket, [number, number]> = {
  "<1k": [2, 2],
  "1-5k": [3, 4],
  "5-15k": [5, 7],
  ">15k": [8, 12],
};

function pickComparable(type: ProtocolType): Proposal["comparable"] {
  const match = (clients as { name: string; protocolType: string; engagementHint: string }[]).find(
    (c) => c.protocolType === type,
  );
  if (!match) return null;
  return {
    client: match.name,
    note: match.engagementHint,
  };
}

export function buildProposal(inputs: ScopingInputs, threats: Threat[]): Proposal {
  const [low, high] = WEEKS[inputs.loc];

  const expedited = inputs.urgency === "Expedited";
  const weeksLow = expedited ? Math.max(2, low - 1) : low;
  const weeksHigh = expedited ? Math.max(weeksLow, high - 1) : high;

  const team: string[] = ["Lead Auditor", "Senior Auditor"];
  if (inputs.type === "Layer 2" || inputs.type === "Bridge") team.push("Cryptography Researcher");
  if (inputs.upgradeable) team.push("Upgrade-Path Reviewer");
  if (inputs.integrations.includes("Oracle")) team.push("Oracle Specialist");

  const deliverables = [
    "Interim findings report (mid-engagement)",
    "Final audit report with severity-classified findings",
    "Fix-review pass on remediations",
    "Threat-model document covering: " + threats.map((t) => t.category).join(", "),
  ];
  if (inputs.upgradeable) {
    deliverables.push("Upgrade runbook review (storage layout + privileged-init invariants)");
  }
  if (inputs.type === "Bridge" || inputs.integrations.includes("Cross-chain messaging")) {
    deliverables.push("Cross-chain invariant fuzz suite (Echidna / Foundry harness)");
  }

  const caveats: string[] = [];
  if (expedited) caveats.push("Expedited timelines reduce slack for deep invariant work; scope cuts may be needed.");
  if (inputs.loc === ">15k") caveats.push(">15k LOC engagements are typically split into two phases with a fix-review gate.");
  if (inputs.stack === "Cairo" || inputs.stack === "Rust")
    caveats.push("Non-Solidity stacks require auditor warm-up and tooling allowance in week 1.");

  return {
    weeksLow,
    weeksHigh,
    team,
    deliverables,
    comparable: pickComparable(inputs.type),
    caveats,
  };
}

export function proposalToMarkdown(
  inputs: ScopingInputs,
  threats: Threat[],
  proposal: Proposal,
): string {
  return [
    `# Audit Scoping Proposal - Sigma Prime (mock)`,
    ``,
    `**Protocol type:** ${inputs.type}`,
    `**Primary stack:** ${inputs.stack}`,
    `**Codebase size:** ${inputs.loc} LOC`,
    `**Upgradeable:** ${inputs.upgradeable ? "Yes" : "No"}`,
    `**External integrations:** ${inputs.integrations.length ? inputs.integrations.join(", ") : "None declared"}`,
    `**Urgency:** ${inputs.urgency}`,
    ``,
    `## Threat Model Summary`,
    ...threats.map((t) => `- **${t.vector}** _(${t.category})_ - ${t.why}`),
    ``,
    `## Engagement Outline`,
    `- **Duration:** ${proposal.weeksLow} to ${proposal.weeksHigh} weeks (illustrative estimate)`,
    `- **Team:** ${proposal.team.join(", ")}`,
    `- **Deliverables:**`,
    ...proposal.deliverables.map((d) => ` - ${d}`),
    proposal.comparable
      ? `\n## Comparable Prior Engagement\n_${proposal.comparable.client}_ - ${proposal.comparable.note}`
      : ``,
    proposal.caveats.length
      ? `\n## Caveats\n${proposal.caveats.map((c) => `- ${c}`).join("\n")}`
      : ``,
    ``,
    ``,
    `## Disclaimer`,
    `These numbers are illustrative estimates from a public-domain heuristic, not Sigma Prime`,
    `pricing. Week ranges are derived from a simple LOC bucket map (<1k: 2 wks, 1-5k: 3-4 wks,`,
    `5-15k: 5-7 wks, >15k: 8-12 wks) with a 1-week reduction if "Expedited" is selected. Real`,
    `engagements depend on code quality, test coverage, novelty of the design, and whether the`,
    `team has prior context. Treat this as a conversation starter, not a quote.`,
    ``,
    `_Generated by SigmaScope. For TAM portfolio demonstration only._`,
  ]
    .filter(Boolean)
    .join("\n");
}
